namespace Server.Models.Gallery.ViewModels.Interfaces;

// Represents HTML checkboxes generated by @Html.CheckBoxesFor() in Gallery.cshtml.
// Also helps with polymorphism for the custom validation attribute in CheckboxAttribute.cs.
public interface ICheckbox
{
    bool IsChecked { get; set; }
}